# Generated by Django 4.1.5 on 2023-02-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baked_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(choices=[('6/2', '6 inch 2 layers/ serves 8-12 '), ('6/3', '6 inch 3 layers/ serves 12-15'), ('8/2', '8 inch 2 layers/ serves 14-20'), ('8/3', '8 inch 3 layers/ serves 18-20'), ('10/2', '10 inch 2 layers/ serves 20-32'), ('10/3', '10 inch 3 layers/ serves 20-32')], default='6/2', max_length=20, verbose_name='Serving Size')),
                ('filling', models.CharField(choices=[('FROSTING', 'Frosting'), ('MOOSE', 'Moose'), ('OREO', 'Oreo Crumbles'), ('FRUIT', 'Fruit')], default='FROSTING', max_length=20, verbose_name='Filling')),
                ('frosting', models.CharField(choices=[('BUTTERCREAM', 'Buttercream'), ('CREAM CHEESE', 'Cream Cheese'), ('WHIPPED', 'Whipped Cream')], default='BUTTERCREAM', max_length=20, verbose_name='Frosting')),
                ('addons', models.CharField(choices=[('DRIP', 'Drip Cake'), ('CHOCOSTRAW', 'Chocolate Covered Strawberries'), ('SPRINKLES', 'Sprinkles'), ('SUPRISE', 'Suprise Inside')], default='DRIP', max_length=20, verbose_name='Add Ons')),
                ('additonal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('order_status', models.CharField(default='True', max_length=30)),
                ('baked_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baked_goods')),
            ],
        ),
        migrations.AddField(
            model_name='baked_goods',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
