# Generated by Django 4.1.5 on 2023-02-09 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baked_goods',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bakedgoods'),
            preserve_default=False,
        ),
    ]
