# Generated by Django 4.1.5 on 2023-02-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='baked_goods',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
